# CCIT4092 Data Visualization

## 02 NumPy Revision

Documentation: https://numpy.org/<br>

In [1]:
import numpy as np

### Python

In [49]:
l=list(range(11)) # python list
# type(l)
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
l=['A', 'Hello', 1, 2, 3]
l

['A', 'Hello', 1, 2, 3]

In [4]:
len(l)

5

In [5]:
l[0] = 'B'
l

['B', 'Hello', 1, 2, 3]

In [6]:
l1 = [1,2,3,4,5]
l1 * 3 # repeat the list contents by 3 times

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
## l1 + 3 # Type Error

In [8]:
l2 = ['A', 'B', 'C']
l1 + l2 # Concatentation of lists

[1, 2, 3, 4, 5, 'A', 'B', 'C']

### Creation of 1D array, and its properties

In [9]:
# Create a 1D array with numbers 0 to 10 using arange

array_1d = np.arange(11)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Data type
type(array_1d)

numpy.ndarray

In [11]:
# Shape of the array 
array_1d.shape

(11,)

In [12]:
# Number of dimension
array_1d.ndim

1

In [13]:
# Data type in the array
array_1d.dtype

dtype('int32')

In [14]:
# Length of the 1D array
array_1d.size

11

In [15]:
# Creation of np.array using list 
#                 0 1 2 3 4
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [16]:
# indexing
array[3]

4

In [17]:
array[2] = 10 # mutable
array

array([ 1,  2, 10,  4,  5])

In [18]:
# Arithmetic operations
array * 3

# Note that this is not repeating the array for 3 times. It is different from list operation

array([ 3,  6, 30, 12, 15])

In [19]:
array + 3

array([ 4,  5, 13,  7,  8])

In [20]:
array + array

array([ 2,  4, 20,  8, 10])

### Slicing

In [21]:
array = np.arange(0,21)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [22]:
# Extracting the elements from index=5 to index=9
array[5:10]

array([5, 6, 7, 8, 9])

In [23]:
# Extracting the first 5 elements
array[:5]

array([0, 1, 2, 3, 4])

In [24]:
# Extracting the last 6 elements
array[-6:]

array([15, 16, 17, 18, 19, 20])

In [25]:
# Extracting the elements, from beginning to the end, with step = 2
array[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Creation of 2D arrays

In [26]:
# Reshape array, from 1 x 12 to 4 x 3 

array_2d = np.arange(1,13).reshape(4,3)
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# Create a 2D array (matrix) of size 4 x 6 
m1 = np.random.randn(4, 6)
m1

array([[ 0.7471453 ,  1.06773   , -0.93196685, -1.08198468, -1.79344599,
         0.47245965],
       [-1.73920544, -2.0740934 , -0.16054604,  0.26939096, -1.00614348,
        -0.42067409],
       [-0.85852225,  1.10507022, -0.6649096 , -0.63074955, -0.45356099,
         0.37433039],
       [ 0.24009939, -0.19653852,  0.23283158, -0.66194202, -0.2181325 ,
        -1.65158702]])

### Slicing on 2D arrays

In [28]:
array_2d = np.arange(1,25).reshape(4,6)
array_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [29]:
# 2nd row
array_2d[1]

array([ 7,  8,  9, 10, 11, 12])

In [30]:
# 2nd to 4th row
array_2d[1:]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
# 3rd to 5th column
array_2d[:,2:5]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [32]:
# 3rd to 5th column
array_2d[1:3,2:5]

array([[ 9, 10, 11],
       [15, 16, 17]])

In [33]:
# 4th column
array_2d[:,3]

array([ 4, 10, 16, 22])

### Filtering

In [50]:
array_2d = np.arange(1,25).reshape(4,6)
array_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [51]:
# Boolean indexing. Those values that are >= 10 will be True, False otherwise
array_2d>=10

array([[False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [52]:
# Filter all the values < 10, only remain those >= 10
array_2d[array_2d>=10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

### Aggregations

In [37]:
data = np.random.random(100)
data

array([0.9997465 , 0.47563305, 0.57017054, 0.03371528, 0.12796815,
       0.81457614, 0.6230378 , 0.62301816, 0.39173607, 0.80632027,
       0.99765606, 0.03468953, 0.65116358, 0.58435206, 0.9190585 ,
       0.43922184, 0.10510033, 0.12300793, 0.14110454, 0.75027487,
       0.95867176, 0.8659251 , 0.04774649, 0.03137419, 0.02078194,
       0.5914745 , 0.31088757, 0.67270304, 0.67616155, 0.55905432,
       0.9161237 , 0.68616245, 0.4449584 , 0.48808131, 0.04053878,
       0.50417106, 0.86526749, 0.11984694, 0.2662479 , 0.26271812,
       0.10937883, 0.24694799, 0.07649185, 0.0981357 , 0.31841693,
       0.1405469 , 0.6101251 , 0.61566396, 0.43913676, 0.93617405,
       0.8283796 , 0.56971623, 0.35626699, 0.62628907, 0.38381433,
       0.28171905, 0.66240745, 0.69729211, 0.00378323, 0.78844644,
       0.55756983, 0.49000113, 0.23747151, 0.64672463, 0.85426816,
       0.2578922 , 0.95539856, 0.15117572, 0.05857381, 0.46486521,
       0.55746934, 0.12002995, 0.68368897, 0.91974338, 0.21737

In [38]:
np.sum(data)

48.74290928811567

In [39]:
np.max(data)

0.9997465039156779

In [40]:
np.argmax(data)

0

In [41]:
np.mean(data)

0.4874290928811567

In [42]:
np.var(data)

0.08276037057529732

### Mathematical functions

In [43]:
# https://numpy.org/doc/1.18/reference/routines.math.html

arr = np.arange(10)
print(arr,'\n')

print(np.sqrt(arr),'\n')
print(np.exp(arr),'\n')

x = np.random.rand(8)
y = np.random.rand(8)
print(x,'\n')
print(y,'\n')
print(np.maximum(x,y))

[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 

[0.7943645  0.69860056 0.26821665 0.35512561 0.25916293 0.22497625
 0.52111605 0.33344748] 

[0.98464039 0.76123185 0.00225397 0.99722167 0.01557176 0.10638571
 0.06372398 0.99592502] 

[0.98464039 0.76123185 0.26821665 0.99722167 0.25916293 0.22497625
 0.52111605 0.99592502]


In [44]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
np.sum(arr,axis=0)

array([15, 18, 21, 24, 27])

### Linear Algebra

In [46]:
# Transposing Arrays and Swapping Axes

arr = np.arange(15).reshape((3,5))
print(arr,'\n')
print(arr.T,'\n')

arr = np.arange(16)
print(arr,'\n')
arr = np.arange(16).reshape((2,2,4))
print(arr,'\n')
print(arr.swapaxes(1,2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [47]:
# Linear Algebra (Matrix - Dot Product)

x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
print(x,'\n')
print(y,'\n')
print(x.dot(y),'\n')

[[1. 2. 3.]
 [4. 5. 6.]] 

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]] 

[[ 28.  64.]
 [ 67. 181.]] 



In [48]:
# Linear Algebra - Inverse

from numpy.linalg import inv
x = np.arange(25).reshape(5,5)
print(x,'\n')
print(x.T,'\n')  # transpose

mat = x.dot(x.T) # dot product
mat

inv(mat) # inverse

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]] 



LinAlgError: Singular matrix

### Loading data using Numpy

In [61]:
# https://archive.ics.uci.edu/ml/datasets/Ionosphere
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'
data= np.genfromtxt(url, delimiter=',', dtype='object')
data

array([[b'1', b'0', b'0.99539', ..., b'0.18641', b'-0.45300', b'g'],
       [b'1', b'0', b'1', ..., b'-0.13738', b'-0.02447', b'b'],
       [b'1', b'0', b'1', ..., b'0.56045', b'-0.38238', b'g'],
       ...,
       [b'1', b'0', b'0.94701', ..., b'0.92697', b'-0.00577', b'g'],
       [b'1', b'0', b'0.90608', ..., b'0.87403', b'-0.16243', b'g'],
       [b'1', b'0', b'0.84710', ..., b'0.85764', b'-0.06151', b'g']],
      dtype=object)

In [62]:
data.shape

(351, 35)

In [63]:
column3= np.genfromtxt(url, delimiter=',', dtype='object', usecols=[5])

np.min(column3)
np.argmin(column3)

245